title: TechBlog Organising of Experience
email: arun.electrosoft@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog Template for Jekyll with GitHub Pages and Bootstrap integrated. 
  This template is tested with latest Bootstrap 4 features. 
baseurl: /TechMemory
url: https://arunelectrosoft.github.io/
github_username:  arunelectrosofts
markdown: kramdown


collections_dir: blogContents
collections:
  Software:
    output: true
    permalink: /:collection/:path
  Electronics:
    output: true
    permalink: /:collection/:path
  GeneralTopics:
    output: true
    permalink: /:collection/:path
  Projects:
    output: true
    permalink: /:collection/:path
  DigitalLibrary:
    output: true
    permalink: /:collection/:path

exclude:
  - Gemfile
  - Gemfile.lock


plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: assets
  style: compressed


  # List of Categories to be used
  # Linux
  # Blogging
  # DIY
  # SubjSkill
  # Programming
  # Chemistry
  # Maths
  # Physics