title: Technical Memory
email: arun.electrosoft@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog Template for Jekyll with GitHub Pages and Bootstrap integrated. 
  This template is tested with latest Bootstrap 4 features. 
baseurl:
# Working baseurl for github.io  baseurl: /TechMemory
# also url for webpage till in github.io is  url: https://arunelectrosoft.github.io/
url: https://www.creativesaplings.com
github_username:  arunelectrosoft
markdown: kramdown


collections_dir: blogContents
collections:
  Software:
    output: true
    permalink: /:collection/:path
  Electronics:
    output: true
    permalink: /:collection/:path
  GeneralTopics:
    output: true
    permalink: /:collection/:path
  Projects:
    output: true
    permalink: /:collection/:path
  DigitalLibrary:
    output: true
    permalink: /:collection/:path
  WebPageTemplate:
    output: true
    permalink: /:collection/:path

exclude:
  - Gemfile
  - Gemfile.lock


plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: assets
  style: compressed


  # List of Categories to be used
  # OSTips
  # Blogging
  # DIY
  # DigitalLibrary
  # Programming
  # Chemistry
  # Maths
  # Physics


#AgriCulture Blog Topics in Future:
#  FarmHouse:
#  EnergyProduction:
#  OrganicAgriculture:
#  FarmAnimals:
#  FarmEquipments:
#  MarketAnalysis:
#  GovtSchemes:
#  siteTestingPosts:

